// Broad General American IPA per unit, from a lexicon generated by tools/build-ipa.ts
// (CMU primary pronunciations converted with the library convention; AI-generated, not
// verified against recordings).
import LEX from "../generated/ipa-lexicon.json";
import { numberWords } from "./compose";

const lex = LEX as Record<string, string>;

function wordsOf(en: string): string[] {
  const out: string[] = [];
  for (const tok of en.split(/\s+/)) {
    if (/^\$?\d+([.:]\d+)?$/.test(tok.replace(/[.,!?;:]+$/, ""))) {
      const t = tok.replace(/[.,!?;:]+$/, "").replace("$", "");
      if (t.includes(":")) { const [h, m] = t.split(":").map(Number); out.push(...numberWords(h).split(/[\s-]+/)); if (m) out.push(...(m < 10 ? ["oh", ...numberWords(m).split(/[\s-]+/)] : numberWords(m).split(/[\s-]+/))); continue; }
      if (t.includes(".")) { const [d, c] = t.split(".").map(Number); out.push(...numberWords(d).split(/[\s-]+/)); if (c) out.push(...numberWords(c).split(/[\s-]+/)); continue; }
      out.push(...numberWords(Number(t)).split(/[\s-]+/));
      continue;
    }
    for (const part of tok.split(/[—–]+|-(?=[A-Za-z])/)) {
      const w = part.replace(/^[^\p{L}0-9'’]+|[^\p{L}0-9'’]+$/gu, "").replace(/’/g, "'").toLowerCase();
      if (w) out.push(w);
    }
  }
  return out;
}

export function ipaForUnit(en: string): string {
  return wordsOf(en).map((w) => lex[w] ?? lex[w.replace(/'s$/, "")] ?? "").filter(Boolean).join(" ");
}

export const hasIpa = () => Object.keys(lex).length > 0;
