// Regenerate src/content/situations/index.ts from the files in the folder.
import fs from "node:fs";
import path from "node:path";
const dir = path.resolve("src/content/situations");
// sNN-…: the situation songs (31–35, 62–91); pNN-…: the advanced songs (P25–P30)
const files = fs.readdirSync(dir).filter((f) => /^[sp]\d\d[a-z]?-.+\.ts$/.test(f)).sort();
const names = files.map((f) => "S_" + f.replace(/\.ts$/, "").replace(/[^a-zA-Z0-9]/g, "_"));
const out = `// All situations (generated by tools/gen-index.ts — run it after adding a file).
import type { SituationDef } from "../types";
${files.map((f, i) => `import ${names[i]} from "./${f.replace(/\.ts$/, "")}";`).join("\n")}

export const SITUATIONS: SituationDef[] = [${names.join(", ")}];
export const SITUATION_BY_ID: Record<string, SituationDef> = Object.fromEntries(SITUATIONS.map((s) => [s.id, s]));
`;
fs.writeFileSync(path.join(dir, "index.ts"), out);
console.log(`index.ts: ${files.length} situations`);
